messages:
  prefix: "&eCustomDrops &7>>"
  general:
    noPlayer: "%prefix% &cYou're not a Player!"
    noPermission: "%prefix% &cYou don't have that permission!"
    configReloaded: "%prefix% &2Config Reloaded!"
    wrongArguments: "%prefix% &cWrong Arguments!"
  gui:
    firstPage: "%prefix% &cYou're already on the first page!"
    lastPage: "%prefix% &cYou're on the last page!"
    alreadyExist: "%prefix% &cTo add another Item, you must first delete the existing one."
  inventory:
    full: "%prefix% &cYour inventory is full!"

gui:
  general:
    items:
      previousPage:
        name: "&e<-- Previous Page"
        lore:
          - ""
          - "&7Opens the previous page."
        material: STONE_BUTTON
      close:
        name: "&cClose"
        lore:
          - ""
          - "&7Closes the GUI."
        material: BARRIER
      nextPage:
        name: "&eNext Page -->"
        lore:
          - ""
          - "&7Opens the next page."
        material: STONE_BUTTON
  customDropEditing:
    title: "&eCustomDrops &7>> &eCustom Drop Editing"
    items:
      type:
        name: "&7Drop Type(&e%customdrop_type%&7)"
        lore:
          - ""
          - "&7Changes the Drop Type."
        material: NAME_TAG
      add:
        name: "&eAdd &eCustom Drop"
        lore:
          - ""
          - "&7Opens a GUI where you will have to select"
          - "&7an item from your inventory, in order"
          - "&7to Add a Custom Drop."
        material: EMERALD
  itemSelection:
    title: "&eCustomDrops &7>> &eSelect Item"

customDropsSettings:
  silkTouch:
    enabled: true
    worlds:
      - "world"