updateCheck: true

messages:
  prefix: "&eCustomDrops &7>>"
  general:
    noPlayer: "%prefix% &cYou're not a Player!"
    noPermission: "%prefix% &cYou don't have that permission!"
    configReloaded: "%prefix% &2Config Reloaded!"
    wrongArguments: "%prefix% &cWrong Arguments!"
  updateCheck:
    latestVersion: "%prefix% &aThis is the latest version(%current_version%) of the plugin."
    newVersionAvailable:
      - "%prefix% &eThere is a new version(%new_version%) available."
      - "%prefix% &eYou can download it at: https://www.spigotmc.org/resources/customdrops-1-8-1-21-1-gui-custom-conditions-custom-actions.119471/"
  gui:
    firstPage: "%prefix% &cYou're already on the first page!"
    lastPage: "%prefix% &cYou're on the last page!"
    alreadyExist: "%prefix% &cTo add another Item, you must first delete the existing one."
  inventory:
    full: "%prefix% &cYour inventory is full!"

gui:
  general:
    items:
      previousPage:
        name: "&e<-- Previous Page"
        lore:
          - ""
          - "&7Opens the previous page."
        material: STONE_BUTTON
      close:
        name: "&cClose"
        lore:
          - ""
          - "&7Closes the GUI."
        material: BARRIER
      nextPage:
        name: "&eNext Page -->"
        lore:
          - ""
          - "&7Opens the next page."
        material: STONE_BUTTON

customDropsSettings:
  silkTouch:
    enabled: true
    worlds:
      - "world"